/**
 * KCS API
 * KCS API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAssemblyPartSearchCriteria.h
 *
 * Критерии поиска и отбора модели при поиске
 */

#ifndef OAIAssemblyPartSearchCriteria_H
#define OAIAssemblyPartSearchCriteria_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAssemblyPartSearchCriteria : public OAIObject {
public:
    OAIAssemblyPartSearchCriteria();
    OAIAssemblyPartSearchCriteria(QString json);
    ~OAIAssemblyPartSearchCriteria() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAssemblyPartSearchCriteria)

#endif // OAIAssemblyPartSearchCriteria_H
