/**
 * KCS API
 * KCS API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIAssemblyPartSearchCriteria.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIAssemblyPartSearchCriteria::OAIAssemblyPartSearchCriteria(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIAssemblyPartSearchCriteria::OAIAssemblyPartSearchCriteria() {
    this->initializeModel();
}

OAIAssemblyPartSearchCriteria::~OAIAssemblyPartSearchCriteria() {}

void OAIAssemblyPartSearchCriteria::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;
}

void OAIAssemblyPartSearchCriteria::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIAssemblyPartSearchCriteria::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;
}

QString OAIAssemblyPartSearchCriteria::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIAssemblyPartSearchCriteria::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    return obj;
}

QString OAIAssemblyPartSearchCriteria::getId() const {
    return id;
}
void OAIAssemblyPartSearchCriteria::setId(const QString &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAIAssemblyPartSearchCriteria::is_id_Set() const{
    return m_id_isSet;
}

bool OAIAssemblyPartSearchCriteria::is_id_Valid() const{
    return m_id_isValid;
}

bool OAIAssemblyPartSearchCriteria::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIAssemblyPartSearchCriteria::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
