/**
 * KCS API
 * KCS API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200.h
 *
 * 
 */

#ifndef OAIInline_response_200_H
#define OAIInline_response_200_H

#include <QJsonObject>

#include "ru.ascin.kcs.api.qt5cpp.model\OAIAssembly.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIInline_response_200 : public OAIObject {
public:
    OAIInline_response_200();
    OAIInline_response_200(QString json);
    ~OAIInline_response_200() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIAssembly> getAssemblies() const;
    void setAssemblies(const QList<OAIAssembly> &assemblies);
    bool is_assemblies_Set() const;
    bool is_assemblies_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAIAssembly> assemblies;
    bool m_assemblies_isSet;
    bool m_assemblies_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIInline_response_200)

#endif // OAIInline_response_200_H
