/**
 * KCS API
 * KCS API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIDefaultApi_H
#define OAI_OAIDefaultApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"

#include "ru.ascin.kcs.api.qt5cpp.model\OAIAssemblyPartSearchCriteria.h"
#include "ru.ascin.kcs.api.qt5cpp.model\OAIInline_object.h"
#include "ru.ascin.kcs.api.qt5cpp.model\OAIInline_response_200.h"
#include "ru.ascin.kcs.api.qt5cpp.model\OAIInline_response_200_1.h"
#include "ru.ascin.kcs.api.qt5cpp.model\OAIInline_response_200_2.h"
#include "ru.ascin.kcs.api.qt5cpp.model\OAIInline_response_201.h"
#include "ru.ascin.kcs.api.qt5cpp.model\OAIObject.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIDefaultApi : public QObject {
    Q_OBJECT

public:
    OAIDefaultApi(const int timeOut = 0);
    ~OAIDefaultApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(QString style);
    QString getParamStyleSuffix(QString style);
    QString getParamStyleDelimiter(QString style, QString name, bool isExplode);

    /**
    * @param[in]  project_id QString [required]
    * @param[in]  oai_assembly_part_search_criteria OAIAssemblyPartSearchCriteria [optional]
    */
    void assemblyPart_getByCriteria(const QString &project_id, const ::OpenAPI::OptionalParam<OAIAssemblyPartSearchCriteria> &oai_assembly_part_search_criteria = ::OpenAPI::OptionalParam<OAIAssemblyPartSearchCriteria>());

    /**
    * @param[in]  project_id QString [required]
    * @param[in]  guid QString [required]
    */
    void assemblyPart_getByGuid(const QString &project_id, const QString &guid);

    /**
    * @param[in]  project_id QString [required]
    */
    void assembly_save(const QString &project_id);

    /**
    * @param[in]  guid QString [required]
    * @param[in]  project_id QString [required]
    */
    void model_getAssemblyByGuid(const QString &guid, const QString &project_id);

    /**
    * @param[in]  content_type_application_x_www_form_urlencoded QString [required]
    * @param[in]  authorization_basic_clientsecret QString [required]
    * @param[in]  oai_inline_object OAIInline_object [optional]
    */
    void postOauthToken(const QString &content_type_application_x_www_form_urlencoded, const QString &authorization_basic_clientsecret, const ::OpenAPI::OptionalParam<OAIInline_object> &oai_inline_object = ::OpenAPI::OptionalParam<OAIInline_object>());

    /**
    * @param[in]  guid QString [required]
    * @param[in]  project_id QString [required]
    */
    void workspace_getByGuid(const QString &guid, const QString &project_id);

    /**
    * @param[in]  project_id QString [required]
    * @param[in]  body OAIObject [optional]
    */
    void workspace_save(const QString &project_id, const ::OpenAPI::OptionalParam<OAIObject> &body = ::OpenAPI::OptionalParam<OAIObject>());


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> defaultHeaders;
    bool isResponseCompressionEnabled;
    bool isRequestCompressionEnabled;

    void assemblyPart_getByCriteriaCallback(OAIHttpRequestWorker *worker);
    void assemblyPart_getByGuidCallback(OAIHttpRequestWorker *worker);
    void assembly_saveCallback(OAIHttpRequestWorker *worker);
    void model_getAssemblyByGuidCallback(OAIHttpRequestWorker *worker);
    void postOauthTokenCallback(OAIHttpRequestWorker *worker);
    void workspace_getByGuidCallback(OAIHttpRequestWorker *worker);
    void workspace_saveCallback(OAIHttpRequestWorker *worker);

signals:

    void assemblyPart_getByCriteriaSignal(OAIInline_response_200_1 summary);
    void assemblyPart_getByGuidSignal(OAIInline_response_200_1 summary);
    void assembly_saveSignal();
    void model_getAssemblyByGuidSignal(OAIInline_response_200 summary);
    void postOauthTokenSignal(OAIInline_response_200_2 summary);
    void workspace_getByGuidSignal(OAIObject summary);
    void workspace_saveSignal();

    void assemblyPart_getByCriteriaSignalFull(OAIHttpRequestWorker *worker, OAIInline_response_200_1 summary);
    void assemblyPart_getByGuidSignalFull(OAIHttpRequestWorker *worker, OAIInline_response_200_1 summary);
    void assembly_saveSignalFull(OAIHttpRequestWorker *worker);
    void model_getAssemblyByGuidSignalFull(OAIHttpRequestWorker *worker, OAIInline_response_200 summary);
    void postOauthTokenSignalFull(OAIHttpRequestWorker *worker, OAIInline_response_200_2 summary);
    void workspace_getByGuidSignalFull(OAIHttpRequestWorker *worker, OAIObject summary);
    void workspace_saveSignalFull(OAIHttpRequestWorker *worker);

    void assemblyPart_getByCriteriaSignalE(OAIInline_response_200_1 summary, QNetworkReply::NetworkError error_type, QString error_str);
    void assemblyPart_getByGuidSignalE(OAIInline_response_200_1 summary, QNetworkReply::NetworkError error_type, QString error_str);
    void assembly_saveSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void model_getAssemblyByGuidSignalE(OAIInline_response_200 summary, QNetworkReply::NetworkError error_type, QString error_str);
    void postOauthTokenSignalE(OAIInline_response_200_2 summary, QNetworkReply::NetworkError error_type, QString error_str);
    void workspace_getByGuidSignalE(OAIObject summary, QNetworkReply::NetworkError error_type, QString error_str);
    void workspace_saveSignalE(QNetworkReply::NetworkError error_type, QString error_str);

    void assemblyPart_getByCriteriaSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void assemblyPart_getByGuidSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void assembly_saveSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void model_getAssemblyByGuidSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void postOauthTokenSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void workspace_getByGuidSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void workspace_saveSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();
};

} // namespace OpenAPI
#endif
