/**
 * KCS API
 * KOMPAS Collaboration Service API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAssembly.h
 *
 * Точная электронная модель - электронная модель детали или сборочной единицы в твердотельном представлении без истории построения и без вспомогательных построений
 */

#ifndef OAIAssembly_H
#define OAIAssembly_H

#include <QJsonObject>

#include "OAIGuid.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAssembly : public OAIObject {
public:
    OAIAssembly();
    OAIAssembly(QString json);
    ~OAIAssembly() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    OAIGuid getModelGuid() const;
    void setModelGuid(const OAIGuid &model_guid);
    bool is_model_guid_Set() const;
    bool is_model_guid_Valid() const;

    QString getDateTime() const;
    void setDateTime(const QString &date_time);
    bool is_date_time_Set() const;
    bool is_date_time_Valid() const;

    QString getHash() const;
    void setHash(const QString &hash);
    bool is_hash_Set() const;
    bool is_hash_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    OAIGuid model_guid;
    bool m_model_guid_isSet;
    bool m_model_guid_isValid;

    QString date_time;
    bool m_date_time_isSet;
    bool m_date_time_isValid;

    QString hash;
    bool m_hash_isSet;
    bool m_hash_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAssembly)

#endif // OAIAssembly_H
