/**
 * KCS API
 * KCS API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAssemblyPartSearchCriteria.h
 *
 * Параметры поиска окружения
 */

#ifndef OAIAssemblyPartSearchCriteria_H
#define OAIAssemblyPartSearchCriteria_H

#include <QJsonObject>

#include "OAILimitingBox.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAssemblyPartSearchCriteria : public OAIObject {
public:
    OAIAssemblyPartSearchCriteria();
    OAIAssemblyPartSearchCriteria(QString json);
    ~OAIAssemblyPartSearchCriteria() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAILimitingBox getLimitingBox() const;
    void setLimitingBox(const OAILimitingBox &limiting_box);
    bool is_limiting_box_Set() const;
    bool is_limiting_box_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAILimitingBox limiting_box;
    bool m_limiting_box_isSet;
    bool m_limiting_box_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAssemblyPartSearchCriteria)

#endif // OAIAssemblyPartSearchCriteria_H
