/**
 * KCS API
 * KOMPAS Collaboration Service API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICoordinate.h
 *
 * Координата точки в пространстве
 */

#ifndef OAICoordinate_H
#define OAICoordinate_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAICoordinate : public OAIObject {
public:
    OAICoordinate();
    OAICoordinate(QString json);
    ~OAICoordinate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getX() const;
    void setX(const double &x);
    bool is_x_Set() const;
    bool is_x_Valid() const;

    double getY() const;
    void setY(const double &y);
    bool is_y_Set() const;
    bool is_y_Valid() const;

    double getZ() const;
    void setZ(const double &z);
    bool is_z_Set() const;
    bool is_z_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double x;
    bool m_x_isSet;
    bool m_x_isValid;

    double y;
    bool m_y_isSet;
    bool m_y_isValid;

    double z;
    bool m_z_isSet;
    bool m_z_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICoordinate)

#endif // OAICoordinate_H
