/**
 * KCS API
 * KCS API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIInline_object.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIInline_object::OAIInline_object(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIInline_object::OAIInline_object() {
    this->initializeModel();
}

OAIInline_object::~OAIInline_object() {}

void OAIInline_object::initializeModel() {

    m_grant_type_isSet = false;
    m_grant_type_isValid = false;

    m_username_isSet = false;
    m_username_isValid = false;

    m_password_isSet = false;
    m_password_isValid = false;
}

void OAIInline_object::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIInline_object::fromJsonObject(QJsonObject json) {

    m_grant_type_isValid = ::OpenAPI::fromJsonValue(grant_type, json[QString("grant_type")]);
    m_grant_type_isSet = !json[QString("grant_type")].isNull() && m_grant_type_isValid;

    m_username_isValid = ::OpenAPI::fromJsonValue(username, json[QString("username")]);
    m_username_isSet = !json[QString("username")].isNull() && m_username_isValid;

    m_password_isValid = ::OpenAPI::fromJsonValue(password, json[QString("password")]);
    m_password_isSet = !json[QString("password")].isNull() && m_password_isValid;
}

QString OAIInline_object::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIInline_object::asJsonObject() const {
    QJsonObject obj;
    if (m_grant_type_isSet) {
        obj.insert(QString("grant_type"), ::OpenAPI::toJsonValue(grant_type));
    }
    if (m_username_isSet) {
        obj.insert(QString("username"), ::OpenAPI::toJsonValue(username));
    }
    if (m_password_isSet) {
        obj.insert(QString("password"), ::OpenAPI::toJsonValue(password));
    }
    return obj;
}

QString OAIInline_object::getGrantType() const {
    return grant_type;
}
void OAIInline_object::setGrantType(const QString &grant_type) {
    this->grant_type = grant_type;
    this->m_grant_type_isSet = true;
}

bool OAIInline_object::is_grant_type_Set() const{
    return m_grant_type_isSet;
}

bool OAIInline_object::is_grant_type_Valid() const{
    return m_grant_type_isValid;
}

QString OAIInline_object::getUsername() const {
    return username;
}
void OAIInline_object::setUsername(const QString &username) {
    this->username = username;
    this->m_username_isSet = true;
}

bool OAIInline_object::is_username_Set() const{
    return m_username_isSet;
}

bool OAIInline_object::is_username_Valid() const{
    return m_username_isValid;
}

QString OAIInline_object::getPassword() const {
    return password;
}
void OAIInline_object::setPassword(const QString &password) {
    this->password = password;
    this->m_password_isSet = true;
}

bool OAIInline_object::is_password_Set() const{
    return m_password_isSet;
}

bool OAIInline_object::is_password_Valid() const{
    return m_password_isValid;
}

bool OAIInline_object::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_grant_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_username_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_password_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIInline_object::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_grant_type_isValid && m_username_isValid && m_password_isValid && true;
}

} // namespace OpenAPI
