/**
 * KCS API
 * KCS API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200.h
 *
 * 
 */

#ifndef OAIInline_response_200_H
#define OAIInline_response_200_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIInline_response_200 : public OAIObject {
public:
    OAIInline_response_200();
    OAIInline_response_200(QString json);
    ~OAIInline_response_200() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getAccessToken() const;
    void setAccessToken(const QString &access_token);
    bool is_access_token_Set() const;
    bool is_access_token_Valid() const;

    QString getTokenType() const;
    void setTokenType(const QString &token_type);
    bool is_token_type_Set() const;
    bool is_token_type_Valid() const;

    QString getRefreshToken() const;
    void setRefreshToken(const QString &refresh_token);
    bool is_refresh_token_Set() const;
    bool is_refresh_token_Valid() const;

    double getExpiresIn() const;
    void setExpiresIn(const double &expires_in);
    bool is_expires_in_Set() const;
    bool is_expires_in_Valid() const;

    QString getScope() const;
    void setScope(const QString &scope);
    bool is_scope_Set() const;
    bool is_scope_Valid() const;

    QString getOAuth2SessionId() const;
    void setOAuth2SessionId(const QString &o_auth2_session_id);
    bool is_o_auth2_session_id_Set() const;
    bool is_o_auth2_session_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString access_token;
    bool m_access_token_isSet;
    bool m_access_token_isValid;

    QString token_type;
    bool m_token_type_isSet;
    bool m_token_type_isValid;

    QString refresh_token;
    bool m_refresh_token_isSet;
    bool m_refresh_token_isValid;

    double expires_in;
    bool m_expires_in_isSet;
    bool m_expires_in_isValid;

    QString scope;
    bool m_scope_isSet;
    bool m_scope_isValid;

    QString o_auth2_session_id;
    bool m_o_auth2_session_id_isSet;
    bool m_o_auth2_session_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIInline_response_200)

#endif // OAIInline_response_200_H
