/**
 * KCS API
 * KOMPAS Collaboration Service API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRenderingParams.h
 *
 * Параметры отображения элементов окружения в Workspace
 */

#ifndef OAIRenderingParams_H
#define OAIRenderingParams_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIRenderingParams : public OAIObject {
public:
    OAIRenderingParams();
    OAIRenderingParams(QString json);
    ~OAIRenderingParams() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getRed() const;
    void setRed(const double &red);
    bool is_red_Set() const;
    bool is_red_Valid() const;

    double getGreen() const;
    void setGreen(const double &green);
    bool is_green_Set() const;
    bool is_green_Valid() const;

    double getBlue() const;
    void setBlue(const double &blue);
    bool is_blue_Set() const;
    bool is_blue_Valid() const;

    double getTransparency() const;
    void setTransparency(const double &transparency);
    bool is_transparency_Set() const;
    bool is_transparency_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double red;
    bool m_red_isSet;
    bool m_red_isValid;

    double green;
    bool m_green_isSet;
    bool m_green_isValid;

    double blue;
    bool m_blue_isSet;
    bool m_blue_isValid;

    double transparency;
    bool m_transparency_isSet;
    bool m_transparency_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIRenderingParams)

#endif // OAIRenderingParams_H
