/**
 * KCS API
 * KOMPAS Collaboration Service API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: modievskii_av@ascon.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIWorkspace.h
 *
 * 
 */

#ifndef OAIWorkspace_H
#define OAIWorkspace_H

#include <QJsonObject>

#include "OAIRenderingParams.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIWorkspace : public OAIObject {
public:
    OAIWorkspace();
    OAIWorkspace(QString json);
    ~OAIWorkspace() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    OAIRenderingParams getSimpleSurfaceParams() const;
    void setSimpleSurfaceParams(const OAIRenderingParams &simple_surface_params);
    bool is_simple_surface_params_Set() const;
    bool is_simple_surface_params_Valid() const;

    OAIRenderingParams getFullSurfaceParams() const;
    void setFullSurfaceParams(const OAIRenderingParams &full_surface_params);
    bool is_full_surface_params_Set() const;
    bool is_full_surface_params_Valid() const;

    OAIRenderingParams getSimpleCollectionParams() const;
    void setSimpleCollectionParams(const OAIRenderingParams &simple_collection_params);
    bool is_simple_collection_params_Set() const;
    bool is_simple_collection_params_Valid() const;

    OAIRenderingParams getFullCollectionParams() const;
    void setFullCollectionParams(const OAIRenderingParams &full_collection_params);
    bool is_full_collection_params_Set() const;
    bool is_full_collection_params_Valid() const;

    bool isShow() const;
    void setShow(const bool &show);
    bool is_show_Set() const;
    bool is_show_Valid() const;

    QString getFileRef() const;
    void setFileRef(const QString &file_ref);
    bool is_file_ref_Set() const;
    bool is_file_ref_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    OAIRenderingParams simple_surface_params;
    bool m_simple_surface_params_isSet;
    bool m_simple_surface_params_isValid;

    OAIRenderingParams full_surface_params;
    bool m_full_surface_params_isSet;
    bool m_full_surface_params_isValid;

    OAIRenderingParams simple_collection_params;
    bool m_simple_collection_params_isSet;
    bool m_simple_collection_params_isValid;

    OAIRenderingParams full_collection_params;
    bool m_full_collection_params_isSet;
    bool m_full_collection_params_isValid;

    bool show;
    bool m_show_isSet;
    bool m_show_isValid;

    QString file_ref;
    bool m_file_ref_isSet;
    bool m_file_ref_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIWorkspace)

#endif // OAIWorkspace_H
